name: Deploy Website to GitHub Pages

on:
  push:
    branches:
      - main  # 每次 main 分支有变更，就重新部署网站

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload static site
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # 部署当前目录的 index.html、资源等

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
